'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, Compass, Headphones, ShieldCheck, Sparkles, X, Building2, CalendarDays, ClipboardCheck, Plane } from 'lucide-react';
import type { BaanContent } from '@/lib/baanContent';
import { submitBaanInterest } from '@/actions/baanActions';
import styles from './baan.module.css';
export default function BaanLanding({ content: c }: { content: BaanContent }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [done, setDone] = useState(false);
  useEffect(() => { if (!open) return; const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [open]);
  const openForm = () => { setDone(false); setError(''); setOpen(true); };
  async function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setError('');
    const form = new FormData(e.currentTarget);
    const result = await submitBaanInterest({ name: String(form.get('name') || ''), email: String(form.get('email') || ''), phone: String(form.get('phone') || ''), postcode: String(form.get('postcode') || ''), airport: String(form.get('airport') || ''), packageTier: String(form.get('packageTier') || ''), passengers: Number(form.get('passengers')), days: String(form.get('days') || ''), room: String(form.get('room') || ''), budget: String(form.get('budget') || '') });
    setBusy(false); if (!result.success) setError(result.error || 'Please try again.'); else { setDone(true); if (result.emailWarning) setError('Your enquiry was saved, but email delivery may be delayed.'); }
  }
  return <main className={styles.page}>
    <section className={styles.hero}>
      <div className={styles.heroDecor} aria-hidden="true"><svg viewBox="0 0 350 350"><circle cx="175" cy="175" r="135" fill="none" stroke="currentColor" strokeWidth="1"/><circle cx="175" cy="175" r="96" fill="none" stroke="currentColor" strokeWidth="1"/><path d="M175 25V325M25 175H325M70 70L280 280M280 70L70 280" stroke="currentColor" strokeWidth="1"/></svg></div>
      <div className={styles.heroInner}><div><p className={styles.eyebrow}><Sparkles size={16}/>{c.eyebrow}</p><h1>{c.heading}</h1><p className={styles.heroDesc}>{c.description}</p><div className={styles.heroActions}><button className={styles.cta} onClick={openForm}>{c.heroButton}<ArrowRight size={19}/></button><span><ShieldCheck size={18}/> UK-based enquiry assistance</span></div><div className={styles.heroStats}><span><strong>2027</strong> Hajj season</span><span><strong>BAAN</strong> Package provider</span><span><strong>UK</strong> Reseller support</span></div></div><div className={styles.heroPhoto}>{c.heroImage ? <img src={c.heroImage} alt={c.heroAlt} onError={(e) => { e.currentTarget.style.display = 'none'; }} /> : null}<div className={styles.photoOverlay}><span>MAKKAH • SAUDI ARABIA</span><strong>A journey worth preparing for.</strong></div></div></div>
    </section>
    <section className={styles.intro}><div><p className={styles.kicker}>OFFICIAL PROVIDER RELATIONSHIP</p><h2>{c.introTitle}</h2><p>{c.introText}</p></div><div className={styles.relationship}><div><Building2/><small>HAJJ PACKAGE PROVIDER</small><strong>{c.provider}</strong></div><ArrowRight className={styles.relArrow}/><div><Headphones/><small>UK RESELLER & SUPPORT</small><strong>{c.reseller}</strong></div></div></section>
    <section className={styles.process}><div className={styles.heading}><p className={styles.kicker}>FOUR SIMPLE STEPS</p><h2>From your first enquiry to Hajj preparation</h2><p>Our team is here to help you explore suitable packages.</p></div><div className={styles.steps}>{c.process.map((s, i) => <div className={styles.step} key={i}><div className={styles.stepTop}><span>{String(i+1).padStart(2,'0')}</span>{i===0?<Compass size={25}/>:i===1?<Headphones size={25}/>:i===2?<ClipboardCheck size={25}/>:<CalendarDays size={25}/>}</div><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></section>
    <section className={styles.support}><div className={styles.heading}><p className={styles.kicker}>BRITISH HAJ TRAVEL</p><h2>Support for UK Pilgrims</h2><p>Explore pilgrimage package options available through our partner providers.</p></div><div className={styles.supportCards}>{c.support.map((s,i) => <div key={i} className={styles.supportCard}><span>{i===0?<Headphones/>:i===1?<Building2/>:<CheckCircle2/>}</span><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></section>
    <section className={styles.notice}><div><ShieldCheck size={32}/><div><h2>Important Hajj Package Information</h2><p>{c.notice}</p></div></div></section>
    <section className={styles.faq}><div className={styles.heading}><p className={styles.kicker}>FREQUENTLY ASKED QUESTIONS</p><h2>BAAN Hajj Packages FAQs</h2><p>Common questions about BAAN Holding Hajj packages available through British Haj Travel.</p></div><div className={styles.faqGrid}>{c.faqs.map((f,i) => <details key={i}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</div></section>
    <section className={styles.bottomCta}><div><p className={styles.kicker}>HAJJ 2027</p><h2>Ready to register your interest?</h2><p>Tell us about your requirements and our UK team will be in touch.</p></div><button className={styles.cta} onClick={openForm}>{c.heroButton}<ArrowRight size={19}/></button></section>
    {open && <div className={styles.backdrop} onMouseDown={(e) => { if(e.target===e.currentTarget)setOpen(false); }}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="baan-modal-heading"><button className={styles.close} onClick={() => setOpen(false)} aria-label="Close form"><X/></button>{done ? <div className={styles.success}><CheckCircle2 size={54}/><h2>Thank you for your interest!</h2><p>Your BAAN Holding Hajj enquiry has been received. Our team will contact you.</p>{error && <p role="status">{error}</p>}<button className={styles.cta} onClick={()=>setOpen(false)}>Close</button></div> : <><p className={styles.kicker}>BRITISH HAJ TRAVEL LTD</p><h2 id="baan-modal-heading">Register for Hajj 2027</h2><p>All fields are required. This is an enquiry, not a confirmed booking.</p><form onSubmit={submit} className={styles.form}><label>Name<input name="name" required maxLength={255} autoComplete="name"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Phone<input name="phone" type="tel" required maxLength={50} autoComplete="tel"/></label><label>Postcode<input name="postcode" required maxLength={30} autoComplete="postal-code"/></label><label>Airport<select name="airport" required >{c.airportOptions.map(option=><option key={option} value={option}>{option}</option>)}</select></label><label>Hajj Package<select name="packageTier" required>{c.packageOptions.map(option=><option key={option} value={option}>{option}</option>)}</select></label><label>Number of Passengers<input name="passengers" type="number" min="1" max="100" defaultValue="1" required/></label><label>Number of Days<select name="days" required>{c.durationOptions.map(option=><option key={option} value={option}>{option}</option>)}</select></label><label>Room Size<select name="room" required>{c.roomOptions.map(option=><option key={option} value={option}>{option}</option>)}</select></label><label>Budget per person (GBP)<select name="budget" required>{c.budgetOptions.map(option=><option key={option} value={option}>{option}</option>)}</select></label>{error && <p className={styles.error} role="alert">{error}</p>}<button className={styles.cta} disabled={busy} type="submit">{busy?'Submitting…':'Submit Enquiry'}<Plane size={18}/></button></form></>}</section></div>}
  </main>;
}
