'use client';
import { useState } from 'react';
import Link from 'next/link';
import { saveBaanContent } from '@/actions/baanActions';
import type { BaanContent } from '@/lib/baanContent';
export default function BaanEditor({initial}:{initial:BaanContent}) {
  const [data,setData]=useState<BaanContent>(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  function setField(key:keyof BaanContent,value:any){setData(prev=>({...prev,[key]:value}));}
  function setArray(key:'faqs'|'support'|'process',index:number,field:string,value:string){setData(prev=>({...prev,[key]:prev[key].map((item,i)=>i===index?{...item,[field]:value}:item)}));}
  async function save(){setBusy(true);setMessage('');try { const res=await saveBaanContent(data);setMessage(res.success?'Page saved successfully.':res.error||'Save failed.'); }catch {setMessage('Save failed. Try again.');}finally{setBusy(false);}}
  const input=(label:string,key:keyof BaanContent,textarea=false)=><label className="block mb-5 text-sm font-semibold text-slate-700">{label}{textarea?<textarea className="mt-2 w-full border rounded-lg p-3 min-h-24" value={data[key] as string} onChange={e=>setField(key,e.target.value)}/>:<input className="mt-2 w-full border rounded-lg p-3" value={data[key] as string} onChange={e=>setField(key,e.target.value)}/>}</label>;
  return <div className="max-w-5xl mx-auto px-5 py-10 text-slate-900"><div className="flex flex-wrap items-center justify-between gap-4 mb-8"><div><h1 className="text-3xl font-bold">BAAN Holding Hajj Page</h1><p className="text-slate-500 mt-1">Edit the page content, hero image, process, support cards and FAQs.</p></div><div className="flex gap-3"><Link className="border rounded-lg px-5 py-3" href="/baan-holding-hajj" target="_blank">Preview page ↗</Link><button className="bg-[#101e63] text-white px-6 py-3 rounded-lg font-bold" disabled={busy} onClick={save}>{busy?'Saving…':'Update Page'}</button></div></div>
  <section className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5">Hero Banner</h2>{input('Eyebrow', 'eyebrow')}{input('Main Heading','heading')}{input('Description','description',true)}{input('Button Label','heroButton')}{input('Hero image URL (use Media Center image URL)','heroImage')}{input('Hero image alt text','heroAlt')}<p className="text-xs text-slate-500">Upload the image through your existing Media Center and paste its URL here. The banner uses a responsive image layout.</p></section>
  <section className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5">Introduction and Provider Details</h2>{input('Introduction heading','introTitle')}{input('Introduction content','introText',true)}{input('Package Provider','provider')}{input('Reseller','reseller')}</section>
  {(['process','support'] as const).map(key=><section key={key} className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5 capitalize">{key==='process'?'How It Works':'Support'} Cards</h2>{data[key].map((item,i)=><div className="bg-slate-50 rounded-lg border p-4 mb-3" key={i}><label className="block text-sm font-semibold">Title<input className="w-full border rounded-lg p-3 mt-1" value={item.title} onChange={e=>setArray(key,i,'title',e.target.value)}/></label><label className="block text-sm font-semibold mt-3">Description<textarea className="w-full border rounded-lg p-3 mt-1" value={item.text} onChange={e=>setArray(key,i,'text',e.target.value)}/></label></div>)}</section>)}
  <section className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5">Important Hajj Package Information</h2>{input('Disclaimer','notice',true)}</section>
  <section className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5">Enquiry Form Dropdown Options</h2><p className="text-slate-500 text-sm mb-4">One option per line. These choices appear in the registration popup.</p>{(['airportOptions','packageOptions','durationOptions','roomOptions','budgetOptions'] as const).map(key=><label className="block font-semibold text-sm mb-4" key={key}>{key.replace('Options',' Options')}<textarea className="w-full border rounded-lg p-3 mt-2" rows={4} value={data[key].join('\n')} onChange={e=>setField(key,e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))}/></label>)}</section>
  <section className="bg-white rounded-xl border p-6 mb-6"><h2 className="font-bold text-xl mb-5">Frequently Asked Questions</h2>{data.faqs.map((item,i)=><div className="bg-slate-50 border rounded-lg p-4 mb-3" key={i}><div className="flex justify-between"><span className="text-sm font-bold">FAQ {i+1}</span><button className="text-red-600 text-sm" onClick={()=>setData(prev=>({...prev,faqs:prev.faqs.filter((_,j)=>i!==j)}))}>Remove</button></div><input aria-label="Question" placeholder="Question" className="w-full border rounded-lg p-3 mt-2" value={item.question} onChange={e=>setArray('faqs',i,'question',e.target.value)}/><textarea aria-label="Answer" placeholder="Answer" className="w-full border rounded-lg p-3 mt-2" value={item.answer} onChange={e=>setArray('faqs',i,'answer',e.target.value)}/></div>)}<button className="border rounded-lg px-4 py-2" onClick={()=>setData(prev=>({...prev,faqs:[...prev.faqs,{question:'',answer:''}]}))}>+ Add FAQ</button></section>
  <div className="flex items-center gap-5"><button className="bg-[#101e63] text-white px-7 py-3 rounded-lg font-bold" disabled={busy} onClick={save}>{busy?'Saving…':'Update Page'}</button><span role="status" className="text-sm">{message}</span></div><p className="mt-5 text-sm text-slate-500">Enquiry email recipients (To, CC, BCC) can be edited under <Link className="underline" href="/admin/settings">Settings → Forms → Email Configs</Link>.</p></div>;
}
